---
- name: Install go-junit-report
  become: false
  command: go get -u -v github.com/jstemmer/go-junit-report
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ go_sys_path }}"
  changed_when: false  #Never really know when it updated

